### ISSUE TITLE
Not getting styles and image to render

### ISSUE THREAD

**Issue by ghost** [CultivateHQ/seat_saver-017#3]
Chrome Version 57.0.2987.110 (64-bit)
XUbuntu 16.04
Erlang/OTP: 19 [erts-8.3]
Elixir: 1.4.1
Phoenix: 1.2.1
Node: v6.10.1
Npm: 3.10.10
Elm: 0.18.0

From Part 3 I downloaded from the repo and installed the web/static/css/seatsaver.css and the web/static/assets/images/seat.png.
On completing Part 4 I can't get the ul to render as anything other than a vertical list of numbers somewhat centered on the page.
I deleted both Elm and Elixir build artifacts and cleaned out Chrome history and restarted project, but no change in rendering.

**Comment by urfolomeus** [comment]
@adequateDeveloper thanks for raising. I'll take a look into this later on today and get back to you.

**Comment by urfolomeus** [comment]
@adequateDeveloper what do you get when you finish Part 3?

**Comment by urfolomeus** [comment]
I've started from scratch with the following versions:

Chrome Version 56.0.2924.87 (64-bit)
OSX 10.12.3
Erlang/OTP: 19.1
Elixir: 1.4.2
Phoenix: 1.2.1
Node: 7.7.2
Npm: 4.1.2
Elm: 0.18.0

And it seems to be working for me. Did you copy the CSS file into `web/static/css` and the image file into `web/static/assets/images`?

**Comment by ghost** [comment]
Weird. I verified I copied seatsaver.css from the repo to web/static/css, and seat.png to web/assets/images per Part 3. In Part 3 I didn't get any of the background of the text to render, so I just marched on through Part 4 to see if things would improve, but no change.  Just the foreground work displays (i.e. the seat numbers), but not any of the background image. 
I'll go over my work in Part 3 again, and switch to FF just for grins to see what's going on.

**Comment by urfolomeus** [comment]
Can you link me to your repo please? I can try running that on my setup and see what happens.

**Comment by ghost** [comment]
Thanks Alan, really appreciate it.

My repo is:  https://github.com/adequateDeveloper/butts_in_seats

**Comment by urfolomeus** [comment]
Aha! If you look in your CSS file you'll see that you've downloaded the HTML page that the CSS is on rather than the CSS itself -> https://github.com/adequateDeveloper/butts_in_seats/blob/master/web/static/css/seatsaver.css

Try downloading this instead -> https://raw.githubusercontent.com/CultivateHQ/seat_saver-017/master/web/static/css/seatsaver.css

Same goes with the image. Visit https://github.com/CultivateHQ/seat_saver-017/blob/master/web/static/assets/images/seat.png and click the download button

![example](http://g.recordit.co/7ujCJgKDhf.gif)

**Comment by ghost** [comment]
duh!

Many thanks Alan,

Dan

**Comment by urfolomeus** [comment]
No worries. Happens to the best of us :)
